apiVersion: v1
kind: PersistentVolume
metadata:
    name: pgdata
spec:
    accessModes:
        - ReadWriteOnce
    StorageClassName: manual
    capacity:
        storage: 2Gi
    hostPath:
        path: /data/pgdata1

