apiVersion: v1
kind: Secret
metadata:
  name: {{ template "argocd-postgres-helm.name" . }}-secret
type: Opaque
data:
  postgres-username: "{{ .Values.secret.username }}"
  postgres-password: "{{ .Values.secret.password }}"

