apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "argocd-postgres-helm.name" . }}-deployment
  labels:
    app: {{ template "argocd-postgres-helm.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "argocd-postgres-helm.name" . }}
  serviceName: {{ template "argocd-postgres-helm.name" . }}-service
  template:
    metadata:
      labels:
        app: {{ template "argocd-postgres-helm.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: pgdata
          mountPath: /data/pgdata
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: Scotia2022
        - name: PGDATA
          mountPath: /data/pgdata
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
          storage: 2Gi